---
- name: Setup laptop
  hosts: local
  remote_user: salvarez
  become: no

  roles:
    - macos
    - { role: macos-opt, tags: ['macos-opt'] }
    - { role: vim, tags: ['vim'] }
    - { role: spacemacs, tags: ['spacemacs'] }
    - { role: zsh, tags: ['zsh'] }
    - { role: ml, tags: ['ml'] }
    - { role: tmux, tags: ['tmux'] }
    - { role: set-java-8, tags: ['java'] }
    - { role: games, tags: ['games'] }

