---
- name: Install opt casks
  shell: HOMEBREW_CASK_OPTS="--appdir=~/Applications" brew install --cask gog-galaxy steam whisky battle-net
  register: result
  retries: 30
  until: result is not failed


