---
- name: Clone pyenv
  git:
    repo: https://github.com/pyenv/pyenv.git
    dest: ~/.pyenv
  ignore_errors: yes

- name: Install bzip2 devel
  apt:
    name: libbz2-dev
  become: yes

