---
- name: Upgrade nodejs repos
  shell: curl -sL https://deb.nodesource.com/setup_16.x | bash -
  become: yes

- name: Upgrade nvidia repos
  shell: curl -fsSL https://nvidia.github.io/libnvidia-container/gpgkey | sudo gpg --batch --yes --dearmor -o /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg && curl -s -L https://nvidia.github.io/libnvidia-container/stable/deb/nvidia-container-toolkit.list | sed 's#deb https://#deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://#g' | sudo tee /etc/apt/sources.list.d/nvidia-container-toolkit.list
  become: yes

- name: Upgrade nvidia repos
  shell: sudo apt-get update
  become: yes

- name: Install base packages
  package:
    name: "{{ item }}"
    state: latest
  become: yes
  with_items:
    - rake
    - git
    - zsh
    - vim
    - ranger
    - emacs
    - x11-xkb-utils
    - xvfb
    - ethtool
    - python3-gpg
    - nodejs
    - libffi-dev
    - libreadline-dev
    - libsqlite3-dev
    - exfat-fuse
    - exfatprogs
    - tmux
    - htop
    - latte-dock
    - qt5-style-kvantum
    - qt5-style-kvantum-themes
    - korganizer
    - appmenu-gtk2-module
    - appmenu-gtk3-module
    - kde-spectacle
    - kdepim
    - cmake
    - gnome-calendar
    - openssh-server
    - build-essential
    - zlib1g-dev
    - libffi-dev
    - libssl-dev
    - libbz2-dev
    - libreadline-dev
    - libsqlite3-dev
    - liblzma-dev
    - python3-tk
    - tk-dev
    - ffmpegthumbnailer
    - gnome-sushi
    - nvidia-docker2
    - virtualbox
    - onedrive
    - openfortivpn
    - plasma-nm
    - neovim
    - locales
    - wakeonlan
    - python3
    - python-is-python3
    - python3-venv
    - libgoogle-perftools4
    - libtcmalloc-minimal4

- name: Install locales
  shell: locale-gen en_US.UTF-8
  become: yes

- name: Install rbenv
  shell: /home/linuxbrew/.linuxbrew/bin/brew install rbenv

- name: Install pyenv
  shell: /home/linuxbrew/.linuxbrew/bin/brew install pyenv

- name: Install tkinter
  shell: /home/linuxbrew/.linuxbrew/bin/brew install python-tk

- name: Install openssl
  shell: /home/linuxbrew/.linuxbrew/bin/brew install openssl@3

- name: Install kubectl
  shell: /home/linuxbrew/.linuxbrew/bin/brew install kubectl

- name: Install python packages
  package:
    name: "{{ item }}"
    state: latest
  become: yes
  with_items:
    - python3-pip
    - python3-virtualenv
    - virtualenvwrapper

- name: Install python modules
  pip:
    name: "{{ item }}"
    state: latest
  become: yes
  with_items:
    - virtualenv
    - virtualenvwrapper

- name: Set hibernate timeout
  ansible.builtin.lineinfile:
    path: /etc/systemd/sleep.conf
    line: HibernateDelaySec=90min
  become: yes
  register: sleep_conf

- name: Set login idle behaviour
  ansible.builtin.lineinfile:
    path: /etc/systemd/logind.conf
    line: IdleAction=suspend-then-hibernate
  become: yes
  register: idle_action

- name: Set login timeout
  ansible.builtin.lineinfile:
    path: /etc/systemd/logind.conf
    line: IdleActionSec=30min
  become: yes
  register: idle_time

- name: Set lid with external power (deprecated)
  ansible.builtin.lineinfile:
    path: /etc/systemd/logind.conf
    line: HandleLidSwitchExternalPower=suspend-then-hibernate
    state: absent
  become: yes
  register: lid_external_power_deprecated

- name: Set lid with external power
  ansible.builtin.lineinfile:
    path: /etc/systemd/logind.conf
    line: HandleLidSwitchExternalPower=hibernate
  become: yes
  register: lid_external_power

- name: Set lid with battery (deprecated)
  ansible.builtin.lineinfile:
    path: /etc/systemd/logind.conf
    line: HandleLidSwitch=suspend-then-hibernate
    state: absent
  become: yes
  register: lid_battery_deprecated

- name: Set lid with battery
  ansible.builtin.lineinfile:
    path: /etc/systemd/logind.conf
    line: HandleLidSwitch=hibernate
  become: yes
  register: lid_battery

- name: Raise open files
  lineinfile:
    path: /etc/sysctl.conf
    line: fs.inotify.max_user_watches=1000000
  become: yes
  register: sysctl

- name: Restart sysctl if needed
  shell: sysctl -p
  when: sysctl.changed
  become: yes
