---
- name: Install pyenv
  shell: brew install python zlib pyenv xz python-tk@3.10 && brew link pyenv

- name: Install virtualenv
  shell: brew install virtualenv virtualenvwrapper pyenv-virtualenv pyenv-virtualenvwrapper

