---
- gem:
    name: rake

- name: Download spf
  get_url:
    url: https://spacevim.org/install.sh
    dest: /tmp/sv-bootstrap.sh
    mode: 0755

- name: Install spf
  shell: bash /tmp/sv-bootstrap.sh

- name: Create .SpaceVim.d
  file:
    path: ~/.SpaceVim.d
    state: directory

- name: Set init config
  template:
    src: init.toml
    dest: ~/.SpaceVim.d/init.toml

- name: Install pip vim packages
  shell: pip install pylint yapf autoflake isort coverage jedi pynvim

