---
- gem:
    name: rake

- name: Download spf
  get_url:
    url: https://spacevim.org/install.sh
    dest: /tmp/sv-bootstrap.sh
    mode: 0755

- name: Install spf
  shell: bash /tmp/sv-bootstrap.sh

- name: Set init config
  template:
    src: init.toml
    dest: ~/.SpaceVim.d/init.toml

