---
- name: Install nvim, lazygit and wezterm
  shell: brew install nvim lazygit

- gem:
    name: rake

- name: Create config folder
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "~/.config"

- name: Download lazyman
  git:
    repo: https://github.com/doctorfree/nvim-lazyman
    dest: ~/.config/nvim-Lazyman
  ignore_errors: yes

- name: Install lazyman
  shell: ~/.config/nvim-Lazyman/lazyman.sh -q -Q -y

- name: Install all packages for lazyman
  shell: PATH=$PATH:~/.local/bin ~/.local/bin/lazyman -B -q -Q -y

- name: Install LazyVim configuration
  template:
    src: "{{ item }}"
    dest: "~/.config/nvim-LazyVim/lua/config/{{ item }}"
  with_items:
    - options.lua
    - lazy.lua

- name: Install LazyVim plugin configuration
  template:
    src: "{{ item }}"
    dest: "~/.config/nvim-LazyVim/lua/plugins/{{ item }}"
  with_items:
    - dap-ui.lua
