---
- name: Tap dive
  homebrew_tap:
    name: wagoodman/dive
    state: present

- name: Install opt apps
  shell: brew install dive exiftool htop yarn gnupg postgresql ranger veracrypt

- name: Install handbrake
  shell: brew install --cask handbrake

- name: Install minio
  get_url:
    url: https://dl.min.io/client/mc/release/darwin-amd64/mc
    dest: /usr/local/bin/mc
    mode: 0755
  become: yes

- name: Install opt casks
  shell: brew install --cask mactex-no-gui balenaetcher sensiblesidebuttons grandperspective vlc postman visual-studio-code bettertouchtool clion pycharm intellij-idea dcp-o-matic lm-studio zotero
  register: result
  retries: 30
  until: result is not failed

- name: Install Keynote
  shell: mas install 409183694

- name: Install Numbers
  shell: mas install 409203825

- name: Install Powerpoint
  shell: mas install 462062816

- name: Install OneDrive
  shell: mas install 823766827

- name: Install Pages
  shell: mas install 409201541

- name: Install Xcode
  shell: mas install 497799835

- name: Install Whatsapp
  shell: mas install 310633997

- name: Install Notability
  shell: mas install 360593530

- name: Install pocket extension
  shell: mas install 1477385213

- name: Install vimium
  shell: mas install 1480933944

- name: Link to xcode
  shell: xcode-select -s /Applications/Xcode.app/Contents/Developer
  become: yes

- name: Accept xcodebuild license
  shell: xcodebuild -license accept
  become: yes

- name: Install RDP Client
  shell: mas install 1295203466

- name: Install Intellij IDEA
  shell: brew install --cask intellij-idea
